### ISSUE TITLE
Unable to initialize OpenGL 2.1 (Debian Buster)

### ISSUE THREAD

**Issue by agmckee** [t4saha/celestia-snap-old#1]
Thanks very much for packaging as a snap. I just tried out the snap because the "bintray" Debian repos don't seem to have all the necessary components. The snap installs fine but unfortunately when launching the application I get the following error:

"Celestia was unable to initialize OpenGL 2.1."

`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast`

Any advice or help you can offer would be appreciated. Thank you again for packaging this application as a snap.

**Comment by t4saha** [comment]
Please refresh the snap and check ? @agmckee

**Comment by agmckee** [comment]
Your super quick reply took me by surprise, I wasn't able to do this until today sorry for the delay. I have now refreshed the snap. Unfortunately I am still getting the same error.

**Comment by t4saha** [comment]
Does your system has nvidia card ?

**Comment by agmckee** [comment]
Yes.

**Comment by t4saha** [comment]
Currently this is caused by a Snapcraft side bug for the Nvidia driver on Debian but a hack has been implemented here which may work. I don't have any Nvidia card. Therefore can you please refresh the Snap and check it again. @agmckee

**Comment by t4saha** [comment]
[https://github.com/t4saha/celestia-snap/commit/31c5790f0337c8f4a0a512e049140274e83772b0](url)
