### ISSUE TITLE
How to properly install addon

### ISSUE THREAD

**Issue by anidotnet** [t4saha/celestia-snap-old#2]
I tried to install this addon - https://celestia.space/forum/viewtopic.php?f=23&t=20801 using your mentioned steps in snap page. I have unzipped the addon zip file and put the content in the .celestia folder as below

path: /home/anindya/snap/celestia-daily/current/.celestia
content:
```
.
├── new_stars.stc
└── textures
    └── medres
        ├── s4711.png
        ├── s4712.png
        ├── s4713.png
        ├── s4714.png
        ├── s4715.png
        └── s62.png
```

But I could not find the name "Sgr A*" in Celestial browser. I guess I am unable to load the addon properly. So could you please help me out here?

On a separate note, I see in your readme file a screenshot of Sgr A*. So how to search it from the Celestial browser and go there?

**Comment by t4saha** [comment]
1. To use any add on you also have to copy the celestia.cfg from snap installation to path: /home/anindya/snap/celestia-daily/current/, Then rename it to .celestia.cfg and open it and replace the line `ExtrasDirectories [ "extras-standard" "extras"]` with `ExtrasDirectories  [ "extras-standard" "extras" "~/.celestia"]`
2. To use Vision Add on of Sgr A*, first you have to download and copy the original Sgr A* Add on by Luigi C. The new Add on does not create any new star, it just replaces the old one. http://www.celestiamotherlode.net/addon/addon_1543.html

@anidotnet

**Comment by anidotnet** [comment]
I did change the .celestia.cfg file as instructed, but it is not loading.. Can you please provide me the intended content structure of .celestia dir?

And if the addon is loaded properly, how do I find it in the celestia browser? Or is there any other way to confirm if the addon loaded successfully?

**Comment by t4saha** [comment]
Celestia Browser only shows nearest 1000 stars. To go to Sgr A* : Just press enter and type Sgr A* or S4711 or S62

.cfg file is inside current Directory not inside .celestia directory. Copy only add on files inside .celestia directory.

@anidotnet

**Comment by t4saha** [comment]
path: /home/UserName/snap/celestia-daily/current/
.
├──.celestia.cfg
└── .celestia
        ├── new_stars.stc
        └── textures
            └── medres
                ├── s4711.png
                ├── s4712.png
                ├── s4713.png
                ├── s4714.png
                ├── s4715.png
                └── s62.png

**Comment by t4saha** [comment]
var routes = (
  <Route name="App">
    <Route name="Admin">
      <Route name="Users"/>
      <Route name="Reports"/>
    </Route>
    <Route name="Course">
      <Route name="Assignments"/>
    </Route>
  </Route>

**Comment by t4saha** [comment]
path: /home/User/snap/celestia-daily/current/

```bash
.
├──.celestia.cfg
└── .celestia
    ├── new_stars.stc
    └── textures
        └── medres
            ├── s4711.png
            ├── s4712.png
            ├── s4713.png
            ├── s4714.png
            ├── s4715.png
            └── s62.png
```

**Comment by anidotnet** [comment]
Awesome.. Thanks.. It works..
